# Generated by Django 4.1.3 on 2022-11-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CL', 'Client'), ('SW', 'Store worker'), ('CW', 'Storage worker')], default='CL', max_length=2),
        ),
    ]
