# Generated by Django 4.1.3 on 2022-12-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_test_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user_allow_to_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
