# Generated by Django 4.1.3 on 2022-11-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(verbose_name='Широта')),
                ('y', models.PositiveSmallIntegerField(verbose_name='Долгота')),
                ('full_address', models.CharField(max_length=200, verbose_name='Полный адрес')),
                ('city', models.CharField(max_length=50, verbose_name='Город для отображения')),
                ('description', models.TextField(max_length=500, verbose_name='Описание магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'unique_together': {('x', 'y', 'full_address')},
            },
        ),
    ]
