# Generated by Django 4.1.3 on 2022-12-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_storage_history'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='store',
            name='full_address',
            field=models.CharField(max_length=200, unique=True, verbose_name='Полный адрес'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('full_address',)},
        ),
        migrations.RemoveField(
            model_name='store',
            name='x',
        ),
        migrations.RemoveField(
            model_name='store',
            name='y',
        ),
    ]
