# Generated by Django 4.1.3 on 2022-12-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_unique_together_alter_store_full_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История покупок', 'verbose_name_plural': 'Истории покупок'},
        ),
    ]
