CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "storage_storage" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "shortcut" varchar(20) NOT NULL, "full_address" varchar(100) NOT NULL);
CREATE TABLE IF NOT EXISTS "good_good" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "artikul" integer unsigned NULL UNIQUE CHECK ("artikul" >= 0), "title" varchar(20) NOT NULL, "description" text NOT NULL, "price" integer unsigned NOT NULL CHECK ("price" >= 0), "image_link" varchar(200) NOT NULL, "buy_amount" integer unsigned NULL CHECK ("buy_amount" >= 0));
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "account_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "account_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "account_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "account_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "account_user_groups_user_id_group_id_4d09af3e_uniq" ON "account_user_groups" ("user_id", "group_id");
CREATE INDEX "account_user_groups_user_id_14345e7b" ON "account_user_groups" ("user_id");
CREATE INDEX "account_user_groups_group_id_6c71f749" ON "account_user_groups" ("group_id");
CREATE UNIQUE INDEX "account_user_user_permissions_user_id_permission_id_48bdd28b_uniq" ON "account_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "account_user_user_permissions_user_id_cc42d270" ON "account_user_user_permissions" ("user_id");
CREATE INDEX "account_user_user_permissions_permission_id_66c44191" ON "account_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "store_history" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" datetime NOT NULL, "good_id" bigint NULL REFERENCES "good_good" ("id") DEFERRABLE INITIALLY DEFERRED, "store_id" bigint NULL REFERENCES "store_store" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "account_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "store_history_good_id_dedae11f" ON "store_history" ("good_id");
CREATE INDEX "store_history_store_id_8bf3de5d" ON "store_history" ("store_id");
CREATE INDEX "store_history_user_id_ea8775b9" ON "store_history" ("user_id");
CREATE TABLE IF NOT EXISTS "store_store" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "city" varchar(50) NOT NULL, "description" text NOT NULL, "storage_id" bigint NULL REFERENCES "storage_storage" ("id") DEFERRABLE INITIALLY DEFERRED, "full_address" varchar(200) NOT NULL UNIQUE);
CREATE INDEX "store_store_storage_id_7479de2b" ON "store_store" ("storage_id");
CREATE UNIQUE INDEX "store_store_full_address_0f81ac87_uniq" ON "store_store" ("full_address");
CREATE TABLE IF NOT EXISTS "account_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "role" varchar(2) NOT NULL, "is_user_allow_to_dashboard" bool NOT NULL, "accepted_store_id" bigint NULL REFERENCES "store_store" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "account_user_accepted_store_id_fb097609" ON "account_user" ("accepted_store_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "account_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
