# Generated by Django 4.1.3 on 2022-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikul', models.PositiveIntegerField(verbose_name='Артикул')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('buy_amount', models.PositiveIntegerField(verbose_name='Кол-во раз купили')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title', 'artikul'],
            },
        ),
    ]
