# Generated by Django 4.1.3 on 2022-11-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image_link',
            field=models.URLField(default='https://mik-zrenie.ru/wp-content/uploads/2021/06/foto_not_found-800x675.jpg'),
        ),
        migrations.AlterField(
            model_name='good',
            name='artikul',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='good',
            name='buy_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во раз купили'),
        ),
    ]
